import './globals.css'
import '@fortawesome/fontawesome-free/css/all.css';
import { Inter } from 'next/font/google'
import { Query, QueryClientProvider } from '@tanstack/react-query';
import { queryClient } from './config';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Infisical',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </QueryClientProvider>
  );
}
