export const taxIdTypeNameMap: {
    [key: string]: string;
} = {
    'au_abn': 'Australia ABN',
    'au_arn': 'Australia ARN',
    'bg_uic': 'Bulgaria UIC',
    'br_cnpj': 'Brazil CNPJ',
    'br_cpf': 'Brazil CPF',
    'ca_bn': 'Canada BN',
    'ca_gst_hst': 'Canada GST/HST',
    'ca_pst_bc': 'Canada PST BC',
    'ca_pst_mb': 'Canada PST MB',
    'ca_pst_sk': 'Canada PST SK',
    'ca_qst': 'Canada QST',
    'ch_vat': 'Switzerland VAT',
    'cl_tin': 'Chile TIN',
    'eg_tin': 'Egypt TIN',
    'es_cif': 'Spain CIF',
    'eu_oss_vat': 'EU OSS VAT',
    'eu_vat': 'EU VAT',
    'gb_vat': 'GB VAT',
    'ge_vat': 'Georgia VAT',
    'hk_br': 'Hong Kong BR',
    'hu_tin': 'Hungary TIN',
    'id_npwp': 'Indonesia NPWP',
    'il_vat': 'Israel VAT',
    'in_gst': 'India GST',
    'is_vat': 'Iceland VAT',
    'jp_cn': 'Japan CN',
    'jp_rn': 'Japan RN',
    'jp_trn': 'Japan TRN',
    'ke_pin': 'Kenya PIN',
    'kr_brn': 'South Korea BRN',
    'li_uid': 'Liechtenstein UID',
    'mx_rfc': 'Mexico RFC',
    'my_frp': 'Malaysia FRP',
    'my_itn': 'Malaysia ITN',
    'my_sst': 'Malaysia SST',
    'no_vat': 'Norway VAT',
    'nz_gst': 'New Zealand GST',
    'ph_tin': 'Philippines TIN',
    'ru_inn': 'Russia INN',
    'ru_kpp': 'Russia KPP',
    'sa_vat': 'Saudi Arabia VAT',
    'sg_gst': 'Singapore GST',
    'sg_uen': 'Singapore UEN',
    'si_tin': 'Slovenia TIN',
    'th_vat': 'Thailand VAT',
    'tr_tin': 'Turkey TIN',
    'tw_vat': 'Taiwan VAT',
    'ua_vat': 'Ukraine VAT',
    'us_ein': 'US EIN',
    'za_vat': 'South Africa VAT'
};